### ISSUE TITLE
Response from the API:     APP 服务被禁用

### ISSUE THREAD

**Issue by QingChang166** [ChrisMuir/baidugeo#5]
Hello,

I recently try to use your package for Geocoding. Here is response from running the bmap_get_coords(locs).

**Comment by ChrisMuir** [comment]
Hi QingChang166, I just pushed an update to patch this, to branch [api-upgrade-test](https://github.com/ChrisMuir/baidugeo/tree/api-upgrade-test). Can you try cloning the repo and testing that branch? And please report back the results? Thanks!

**Comment by QingChang166** [comment]
This works! Thank you very much!
